name: Android Build Dynamo Calc

on:
  push:
    branches:
      - main
      - develop
  pull_request:
    branches:
      - main
      - develop

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Set up JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17' # Ensure this matches your project's compileOptions.targetCompatibility
          distribution: 'temurin'
          cache: 'gradle'

      - name: Grant execute permission for gradlew
        run: chmod +x gradlew

      - name: Build Debug APK
        run: ./gradlew assembleDebug

      - name: Upload Debug APK
        uses: actions/upload-artifact@v4
        with:
          name: DynamoCalc-debug-apk
          path: app/build/outputs/apk/debug/app-debug.apk

      - name: Run Unit Tests
        run: ./gradlew testDebugUnitTest

      - name: Upload Unit Test Results
        uses: actions/upload-artifact@v4
        with:
          name: unit-test-results
          path: app/build/reports/tests/testDebugUnitTest/

      # Optional: Add steps for release build, signing, or publishing if needed
      # - name: Build Release APK (requires signing setup)
      #   run: ./gradlew assembleRelease
      #   env:
      #     KEYSTORE_PASSWORD: ${{ secrets.KEYSTORE_PASSWORD }}
      #     KEY_ALIAS: ${{ secrets.KEY_ALIAS }}
      #     KEY_PASSWORD: ${{ secrets.KEY_PASSWORD }}
      #     # Add other necessary signing environment variables here

      # - name: Upload Release APK
      #   if: success() # Only upload if build is successful
      #   uses: actions/upload-artifact@v4
      #   with:
      #     name: DynamoCalc-release-apk
      #     path: app/build/outputs/apk/release/app-release.apk
